collections:
  projects:
    output: true

defaults:
  - scope:
      path: "index.html"
    values:
      layout: ""
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
